extensionId: 87FE44E5-179C-43A3-A87B3D38BEF4652E
luceeCoreVersion: 7.0.4.20
releaseType: server
label: EHCache Extension
description: Integrates EHCache 3 as a high-performance caching provider for Lucee Server
